### ISSUE TITLE
Svg export from Animate cc 

### ISSUE THREAD

**Issue by EvieMur** [cjgammon/SnapSVG-Animator#103]
Hey guys! I have been having troubles exporting the svg animation I have created in flash. I have got the snap svg plug in and everything else in order to make this work. When I try to publish the svg animation the browsers shows a blank page without any of my animation on it. I am not sure what could be the problem, so maybe any of you know the solution or maybe the cause of this. Any little help would be really appreciated :)

Here's the link to it : https://drive.google.com/open?id=0B6gH2DbSnPv8UnpBeDUtUi1KT1U2

I have used the SnapSVGAnimator document in flash to create this simple round shape, because I want the animation to be an svg file. I have also used action script to make the ball change shape when the mouse is on top of it. I am not sure if it works, because whenever I try to test it nothing appears or when I publish it the browser displays an empty window.

**Comment by NigelJLinton** [comment]
Hi EvieMur,

What errors do have when check the console of the browser? This will help determine why it's not displaying.

The Google Drive file isn't currently showing a file not found.

Thanks

**Comment by diannealonsagay** [comment]
I'm having this same problem. The error I see is:

> test.html:45 XMLHttpRequest cannot load file:///Users/d/test.json. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.

**Comment by diannealonsagay** [comment]
Alright, so I searched for the error phrase on google and came across this: https://stackoverflow.com/questions/27742070/angularjs-error-cross-origin-requests-are-only-supported-for-protocol-schemes

The answer to the problem is explained in the top 2 replies from [Tadas Sukys](https://stackoverflow.com/users/135877/tadas-%c5%a0ukys) and [Chirag](https://stackoverflow.com/users/3383766/chirag)

> This error is happening because you are just opening html documents directly from the browser. To fix this you will need to serve your code from a webserver and access it on localhost.

> Go to your app directory
Start SimpleHTTPServer
In the terminal:
`$ cd yourfiledirectory`
`~/yourfiledirectory $ python -m SimpleHTTPServer`

> Now, go to localhost:8000 in your browser and the page will show

Your animation should appear after these steps
