### ISSUE TITLE
error installing using extension manager

### ISSUE THREAD

**Issue by seminice** [cjgammon/SnapSVG-Animator#50]
Hi
I get this error when I install the plugin.
Extension com.example.SnapPlatform doesn't contain a valid signature
any ideas?

**Comment by wosh** [comment]
same here
Extension manager 7.2
Flash 14.2

**Comment by kundugoutam** [comment]
Adobe Extension Manager CC UI is phased out due to its integration with Creative Cloud. You can refer to https://www.adobeexchange.com/resources/27 for details. However, there exists a command line utility that we can use in place of Extension Manager to install Extensions for Flash CC 2015. 

1. Please download the command line utility for your platform. For Windows, you can download it from http://www.adobeexchange.com/ExManCmd_win.zip. For MAC, you can download the utility from http://www.adobeexchange.com/ExManCmd_mac.zip. Extract the downloaded .zip file say to your desktop C:\Users\<your user name>\Desktop\ExManCmd_win

2. Copy paste the extensions(.zxp files) that you want to install to the same folder(C:\Users\<your user name>\Desktop\ExManCmd_win\) where ExManCmd.exe is available for convenience

3. On Windows, open Command Prompt (Start > All Programs > Accessories > Command Prompt) and type cd C:\Users\sampleUser\Desktop\ExManCmd_win

4. Upon successful navigation to the ExManCmd_win folder where there is an exe named ExManCmd.exe and the .zxp files that you have copied in step 2
type ExManCmd.exe /install “<nameoftheExtension.zxp>” and hit Enter (please note that if the extension name has space in between please specify them within “double quotes”) 

Please let us know if you face any issues or need any assistance in getting the extensions up & running for Flash CC 2015.

**Comment by kundugoutam** [comment]
Alternatively, you can install extension through Adobe Creative Cloud. The first version of the extension is available in: https://creative.adobe.com/addons/products/12329#.VaydA_mqpBc.

Please ensure that CC file sync is enabled for the extension to be listed.

**Comment by seminice** [comment]
tried that and this is what I got , 
`./ExManCmd --install "~/Downloads/SnapSvganimator_1_0_0.zxp"
Failed to install, status = -402!`

tried reading the documentation here 
https://helpx.adobe.com/pdf/extension_manager_reference.pdf

followed up with them and same issue.

**Comment by kundugoutam** [comment]
We plan to submit a updated version of the extension soon along with few other improvements. Hopefully, that will fix the issue that you are facing.

**Comment by seminice** [comment]
Cool , if you want any detail or tests feel free to ask.

**Comment by kundugoutam** [comment]
Hi seminice/wosh,

We have updated SnapSVGAnimator.zxp in github. You can find it in the path SnapSVGAnimatorPlatform/EclipseProject in the 'master' branch. Before we upload it to add-ons page, we would request you to try it out and let us know if it resolves your issue.

We have made following changes in this update:

- Added settings in publish settings dialog that will allow you to use minified runtime and reduce output file size.
- Made few performance optimization

Please try it and let us know your feedback.

Thanks.

**Comment by seminice** [comment]
Worked perfectly here!

Thanks, but I have one concern that the output file is really big, and too many dependencies are there, this makes it difficult to port the output in a web application or use this plugin freely , unless your aim in the first place when developed this plugin is to be used for large serious animations, it can't be used for a simple animation or say button animation or UI element (thats what I want to use it for, creating UI elements as angular directives), I will hack on the output the next coming days and I'll let you know if there could be any improvements in the output.

Thank you so much again and good job.

**Comment by kundugoutam** [comment]
Thanks for confirming that you are able to install and use the zxp.

Regarding the output file size (I am guessing you are concerned about JSON size), I hope you are using default publish settings(ie "Minify" and "Compact Data" are turned on). 

What is the kind of size you are getting with Snap? Please compare it with an "uncompressed" SWF size and let us know your findings.

Meanwhile, we continue to work on improving JSON file size and we have an issue to track it. We plan to use tiny names and possibly provide an option to compress JSON using zlib or any such compression library. We have few other ideas which we hope to implement in near future. Feel free to add your comments.

Can you please elaborate on the "dependencies" part bit more?
