### ISSUE TITLE
Getting a blank white screen when exported to SVG

### ISSUE THREAD

**Issue by arjun-dwarakanath** [cjgammon/SnapSVG-Animator#80]
HTML file is blank, white screen after publishing. Output popped up with a warning on animate cc saying

"Blend Modes(Layer) is not supported in SnapSVGAnimator document, and has been converted to Normal in an instance of Movieclip <Group>_4."

When i test it on animate cc it works fine, but when i export it, i cant see any animation.

Can you please help me. 
[Source files.zip](https://github.com/cjgammon/SnapSVG-Animator/files/440986/Source.files.zip)

**Comment by cjgammon** [comment]
The .fla you included publishes for me.  Below is the output I'm getting.  
[Soruce.files.2.zip](https://github.com/cjgammon/SnapSVG-Animator/files/440989/Soruce.files.2.zip)

It looks like the directory structure you included does not include the snap.svg javascript files.  You can see the errors in the console.  Were these removed?  What are your Publish settings?  How are you publishing the movie (File>Publish or Control>Test)?  This seems odd as I've never heard of issues with these files missing.

**Comment by arjun-dwarakanath** [comment]
I am publishing through File > publish. The file you have shared is also not working in my browser. Is any thing wrong in my browser? Tried on chrome as well. When i export i can only see two files ( HTML & json) and a svg folder. 

I have attached a screen shots 

![screen shot 2016-08-28 at 10 45 25 am](https://cloud.githubusercontent.com/assets/21286876/18031796/584807d2-6d0d-11e6-89f5-6c25939d37cf.png)
![screen shot 2016-08-28 at 10 41 59 am](https://cloud.githubusercontent.com/assets/21286876/18031797/58580cfe-6d0d-11e6-91c7-82755808e0c4.png)

**Comment by cjgammon** [comment]
When I opened your .zip there were missing javascript files in the output.  The full generated file structure should look like this:

![screen shot 2016-08-28 at 12 41 43 am](https://cloud.githubusercontent.com/assets/192022/18031860/417fda2a-6cb8-11e6-9bcb-bf425e68f982.png)

It looks like you're trying to open it locally on the file system.  This will not work due to browser security restrictions.  You need to run them on a server.  If you preview from the FLA (CMD + Return) it will launch a local server instance and run the file there.

**Comment by arjun-dwarakanath** [comment]
Yes you are right, i need to run on server. so i can view this output. Any way thank you so much for quick revert.

**Comment by arjun-dwarakanath** [comment]
Hey, is their any way to run this file locally on my system, can we enable these browser securities restrictions

**Comment by cjgammon** [comment]
If you Test the movie (Control->Test) out of the FlA instead of Publishing (File->Publish). It will run a local server and open a browser so you can iterate quickly, that's going to be your best method unless you want to set up a local server yourself with something like MAMP or you could try using a flag in chrome, something like below :
http://stackoverflow.com/questions/18586921/how-to-launch-html-using-chrome-at-allow-file-access-from-files-mode
